#!/usr/bin/env python
# -*- coding: utf8 -*-
from datetime import datetime, timedelta
import sys, os, subprocess, getopt
import time
import socket

def usage():
    print 'babysitter -r user1@dot.com,user2@dot.com command [options]'
    print '-r: comma seperated receivers'
    print '-h: help'

def get_local_ip():  # copy from shenlei's baselib
    """
    return: eg: '122.49.31.140'
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("baidu.com", 80))
    r = s.getsockname()[0]
    s.close()
    return r

def main():
    receivers = []

    opts, args = getopt.getopt(sys.argv[1:], "hr:")
    for op, value in opts:
        if op == "-r":
            receivers = value
        if op == "-h":
            usage()
            return 0

    if not receivers:
        print 'missing -r argument.'
        return 2

    for i in receivers.split(','):
        if '@' not in i:
            print 'bad -r at:', i
            return 2

    if not args:
        print 'missing command.'
        return 2

    wait = 60
    while 1:
        start_time = time.time()

        r = subprocess.call(args)
        if time.time() - start_time < 300: # if exit within 300 seconds
            wait *= 2
        else:
            wait = 1
        ip = get_local_ip()
        msg = 'stopped' if r == 0 else 'crashed'
        email_info = "[babysitter报警: %s on %s is %s.restart command: %s in %d second]" %(
                      args[0], ip, msg, ' '.join(args),wait)
        email_cmd = 'python /usr/bin/sendmail.py \
                     --subject="数据组-服务监控报警" \
                     --body="%s" \
                     --to="%s" \
                     --from-name="internal"' %(email_info,receivers)
        os.system(email_cmd)
        time.sleep(wait)

    sys.exit(1)

if __name__ == "__main__":
    sys.exit(main())

